<template>
  <div class="admin-page art-full-height">
    <ElCard shadow="never" class="search-card"><ElForm :model="searchForm" label-width="82px"><ElRow :gutter="16"><ElCol :xs="24" :md="8"><ElFormItem label="分组"><ElInput v-model="searchForm.group" clearable /></ElFormItem></ElCol><ElCol :xs="24" :md="8"><ElFormItem label="名称"><ElInput v-model="searchForm.name" clearable /></ElFormItem></ElCol><ElCol :xs="24" :md="8" class="search-actions"><ElButton type="primary" :loading="loading" @click="loadData">查询</ElButton><ElButton @click="resetSearch">重置</ElButton></ElCol></ElRow></ElForm></ElCard>
    <ElCard class="art-table-card" shadow="never"><template #header><div class="card-header"><span>接口管理</span><ElSpace><ElButton type="primary" @click="openCreate">新增接口</ElButton><ElButton :loading="loading" @click="loadData">刷新</ElButton></ElSpace></div></template><ElTable v-loading="loading" :data="rows" height="100%" border stripe><ElTableColumn prop="id" label="ID" width="90" /><ElTableColumn prop="group" label="分组" min-width="130" /><ElTableColumn prop="name" label="名称" min-width="160" /><ElTableColumn prop="method" label="方法" width="100"><template #default="{ row }"><ElTag>{{ row.method }}</ElTag></template></ElTableColumn><ElTableColumn prop="path" label="路径" min-width="220" /><ElTableColumn label="操作" width="150" fixed="right"><template #default="{ row }"><ElButton link type="primary" @click="openEdit(row)">编辑</ElButton><ElButton link type="danger" @click="remove(row)">删除</ElButton></template></ElTableColumn></ElTable><ElPagination class="pagination" background layout="total, sizes, prev, pager, next" :total="pagination.total" v-model:current-page="pagination.current" v-model:page-size="pagination.pageSize" @change="loadData" /></ElCard>
    <ElDrawer v-model="drawerVisible" :title="form.id ? '编辑接口' : '新增接口'" size="460px"><ElForm :model="form" :rules="rules" ref="formRef" label-width="90px"><ElFormItem label="分组" prop="group"><ElInput v-model="form.group" /></ElFormItem><ElFormItem label="名称" prop="name"><ElInput v-model="form.name" /></ElFormItem><ElFormItem label="方法" prop="method"><ElSelect v-model="form.method" class="w-full"><ElOption v-for="item in methods" :key="item" :label="item" :value="item" /></ElSelect></ElFormItem><ElFormItem label="路径" prop="path"><ElInput v-model="form.path" /></ElFormItem></ElForm><template #footer><ElButton @click="drawerVisible=false">取消</ElButton><ElButton type="primary" :loading="submitting" @click="submit">提交</ElButton></template></ElDrawer>
  </div>
</template>
<script setup lang="ts">
import { ElMessage, ElMessageBox, type FormInstance } from 'element-plus'
import { createAdminApiApi, deleteAdminApiApi, getAdminApiApi, updateAdminApiApi } from '@/api/admin/permission'
defineOptions({ name: 'AdminApi' })
const methods=['GET','POST','PUT','DELETE','PATCH']; const loading=ref(false); const submitting=ref(false); const rows=ref<any[]>([]); const drawerVisible=ref(false); const formRef=ref<FormInstance>(); const pagination=reactive({current:1,pageSize:20,total:0}); const searchForm=reactive<any>({group:'',name:''}); const form=reactive<any>({}); const rules={group:[{required:true,message:'请输入分组',trigger:'blur'}],name:[{required:true,message:'请输入名称',trigger:'blur'}],method:[{required:true,message:'请选择方法',trigger:'change'}],path:[{required:true,message:'请输入路径',trigger:'blur'}]}
function normalizeList(data:any){return data?.list||data?.records||data?.items||data||[]} function normalizeTotal(data:any,list:any[]){return Number(data?.total??data?.count??list.length??0)} function resetForm(data:any={}){Object.keys(form).forEach((key)=>delete form[key]); Object.assign(form,{id:undefined,group:'',name:'',method:'GET',path:'',...data})}
async function loadData(){loading.value=true; try{const data=await getAdminApiApi({...searchForm,page:pagination.current,pageSize:pagination.pageSize}); const list=normalizeList(data); rows.value=list; pagination.total=normalizeTotal(data,list)}finally{loading.value=false}}
function resetSearch(){searchForm.group='';searchForm.name='';pagination.current=1;loadData()} function openCreate(){resetForm(); drawerVisible.value=true} function openEdit(row:any){resetForm(row); drawerVisible.value=true}
async function remove(row:any){await ElMessageBox.confirm(`确定删除接口「${row.name||row.path}」吗？`,'删除确认',{type:'warning'}); await deleteAdminApiApi({id:row.id}); ElMessage.success('删除成功'); loadData()}
async function submit(){await formRef.value?.validate(); submitting.value=true; try{form.id?await updateAdminApiApi({...form}):await createAdminApiApi({...form}); ElMessage.success('提交成功'); drawerVisible.value=false; loadData()}finally{submitting.value=false}}
onMounted(loadData)
</script>
<style scoped lang="scss">.admin-page{display:flex;flex-direction:column;gap:16px}.search-card{flex:none}.art-table-card{min-height:0}.card-header{display:flex;align-items:center;justify-content:space-between}.search-actions{display:flex;align-items:flex-start}.pagination{justify-content:flex-end;margin-top:16px}.w-full{width:100%}</style>
