// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"nunu-layout-monorepo/app/home/internal/handler"
	"nunu-layout-monorepo/app/home/internal/router"
	"nunu-layout-monorepo/app/home/internal/server"
	"nunu-layout-monorepo/app/home/internal/service"
	"nunu-layout-monorepo/pkg/app"
	"nunu-layout-monorepo/pkg/log"
	"nunu-layout-monorepo/pkg/server/http"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	handlerHandler := handler.NewHandler(logger)
	serviceService := service.NewService(viperViper, logger)
	siteService := service.NewSiteService(serviceService)
	siteHandler := handler.NewSiteHandler(handlerHandler, siteService)
	routerDeps := router.RouterDeps{
		Logger:      logger,
		Config:      viperViper,
		SiteHandler: siteHandler,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	appApp := newApp(httpServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var serviceSet = wire.NewSet(service.NewService, service.NewSiteService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewSiteHandler)

var serverSet = wire.NewSet(server.NewHTTPServer)

func newApp(httpServer *http.Server) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithName("home-server"))
}
